services:
  db:
    extends:
      file: ./packages/server/docker-compose.db.yml
      service: db
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    env_file:
      - packages/server/.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
