version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    env_file:
      - packages/server/.env
    ports:
      - "3000:3000"